spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1

aws:
  region: ${AWS_DEFAULT_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}

logging:
  level:
    org.springframework.r2dbc: DEBUG
    software.amazon.awssdk.s3: DEBUG
    org.springframework: WARN
    root: INFO
