--CREATE TABLE IF NOT EXISTS code_analysis (
--    id VARCHAR(255) PRIMARY KEY,
--    repository_url TEXT NOT NULL,
--    branch_name VARCHAR(255) NOT NULL,
--    status VARCHAR(50) NOT NULL,
--    start_time TIMESTAMP,
--    end_time TIMESTAMP,
--    error_message TEXT,
--    storage_location TEXT
--);
--
--CREATE INDEX IF NOT EXISTS idx_analysis_status ON code_analysis(status);